### ISSUE TITLE
Support 1.21.2

### ISSUE THREAD

**Issue by lesxmore** [MattiDragon/universal-perms#13]
Hi, will Universal Perms be updated to support version 1.21.2?

**Comment by MattiDragon** [comment]
No, but I will soon update to 1.21.3

**Comment by MattiDragon** [comment]
Seems like the old version works. I've updated the modrinth page

**Comment by lesxmore** [comment]
Still doesn't work. Here's the log https://mclo.gs/BNWXIvk

**Comment by MattiDragon** [comment]
I see. I'll get a fix out as soon as possible

**Comment by ZekeZDev** [comment]
has this been fixed, its listed as 1.21.3 on the modrinth page however it doesnt seem to work for me.

**Comment by MattiDragon** [comment]
Seems like my checks were incorrect. I've now published v1.0.7 that actually works on 1.21.3 and 1.21.4
