### ISSUE TITLE
[BUG] I can´t readd/overwrite perms to the owner group that I removed for the Default Group (LuckPerms)

### ISSUE THREAD

**Issue by NextRaven10** [MattiDragon/universal-perms#14]
I don´t really know what else to write here :/
If I can provide any assistance/help/files to speed up the process of fixing it I´m open for it :)

**Comment by MattiDragon** [comment]
This is almost certainly user error, and if it isn't then it's a luckperms issue. I suggest asking for help with your permission setup there

**Comment by NextRaven10** [comment]
yup, was user error 😂😅
Sorry xD
