### ISSUE TITLE
Compatibility with 1.19.3

### ISSUE THREAD

**Issue by Nathanwoodburn** [MattiDragon/universal-perms#2]
G'day, do you know when this will work with 1.19.3?

**Comment by MattiDragon** [comment]
It might already work, I don't remember any major changes that would have affected this mod. Please report any issues so I can fix them

**Comment by Nathanwoodburn** [comment]
OK, I've finally got around to testing it
![image](https://user-images.githubusercontent.com/62039630/208373952-3d03525c-2451-4e87-9090-4a598ba925c3.png)

**Comment by MattiDragon** [comment]
Try a dependency override. That's just what I set it to

**Comment by Nathanwoodburn** [comment]
How do I do that?

**Comment by MattiDragon** [comment]
The fabric wiki has a tutorial on it

**Comment by unilock** [comment]
The dependency on 1.19.2 is hardcoded in `fabric.mod.json`.

https://github.com/MattiDragon/universal-perms/blob/c33db6953b0e3a2c8d70013fa99eeb41a847bf0c/src/main/resources/fabric.mod.json#L28

Changing this to `~1.19` would fix it - but would also allow versions 1.19 and 1.19.1 to try loading the mod, which might not be ideal.

This is the "dependency override" tutorial, by the way:
https://fabricmc.net/wiki/tutorial:dependency_overrides

Just create a file `fabric_loader_dependencies.json` in your `config` folder that contains the following:
```json
{
  "version": 1,
  "overrides": {
    "universal_perms": {
      "depends": {
        "minecraft": "~1.19"
      }
    }
  }
}
```

**Comment by MattiDragon** [comment]
> Changing this to ~1.19 would fix it - but would also allow versions 1.19 and 1.19.1 to try loading the mod, which might not be ideal.

The correct version would probably be `~1.19.2`.

**Comment by unilock** [comment]
Oh, yes, that would work too. I forgot that you can use `~` like that - I thought it would only work with e.g. `~1.18`, and not `~1.18.2`. Whoops.

**Comment by M8torr** [comment]
@MattiDragon the mod seems to work on 1.19.4, but still needs the override.
Would it be possible to build it to allow all 1.19 versions to run it?
Also, can you mark it as compatible with 1.19.4 in Modrinth, so updaters like ferium can download it?

Thanks

**Comment by MattiDragon** [comment]
I'll release a new version that's marked to support more versions
