### ISSUE TITLE
Selectors do not work @s @e

### ISSUE THREAD

**Issue by M8torr** [MattiDragon/universal-perms#4]
The selectors cannot be used in commands like /tp @s

![image](https://user-images.githubusercontent.com/1701084/209318154-11bebd2d-97b6-4ee3-bda2-e6042f7980d0.png)

Would it be possible to add the selectors?

**Comment by MattiDragon** [comment]
I have no idea why this is broken. I'll look into it

**Comment by M8torr** [comment]
There is another mod that has an implementation of the selectors. In case you want to take a look.
https://github.com/DrexHD/VanillaPermissions

Thanks for this amazing mod.

**Comment by MattiDragon** [comment]
I'm implementing support for a bunch of other places vanilla does permission checks. I'll probably release it after christmas

**Comment by MattiDragon** [comment]
I've added a permission to fix it in 1.0.2
