### ISSUE TITLE
Compatibility with 1.18.2

### ISSUE THREAD

**Issue by mike-brown8** [MattiDragon/universal-perms#6]
I need this mod in 1.18.2 indeed! I'v tried and found the problem of its 1.0.0 with MC1.18.2.
![image](https://user-images.githubusercontent.com/87358498/219024314-417fff8b-8a9f-4028-9593-b2633494e227.png)

**Comment by MattiDragon** [comment]
1.18 support isn't planned. I'm open to pull requests, but I'm not interested in backporting the mod
